version: "3"
services:
  llm_edge:
    build:
      context: .
    volumes:
      - .:/playground
    networks:
      - llm_edge_playground
    ports:
      - "3000:3000"
      - "8000:8000"
    tty: true
networks:
  llm_edge_playground:
    driver: bridge